version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:firman341@db:5433/CaptoneProject
    networks:
      - capstone-network
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
  
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_PASSWORD: firman341
      POSTGRES_USER: postgres
      POSTGRES_DB: CaptoneProject
    ports:
      - "5433:5433"
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  capstone-network:
    external: true

volumes:
  db_data:
